---

- name: Install Docker
  hosts: all
  become: true
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
    - role: geerlingguy.docker
      vars:
        # Don't need to start the service during build
        docker_service_manage: false
        docker_install_compose_plugin: false
        # Without this, Docker falls back to VFS.
        # VFS uses more space and can cause GHA runners to run out of space.
        docker_daemon_options:
          storage-driver: overlay2

  tasks:
    - name: Manually enable Docker service for systemd
      ansible.builtin.file:
        src: /lib/systemd/system/docker.service
        dest: /etc/systemd/system/multi-user.target.wants/docker.service
        state: link

    # Not needed for use case, has huge dependencies
    - name: Remove docker-ce-rootless-extras
      ansible.builtin.apt:
        name: docker-ce-rootless-extras
        autoremove: true
        purge: true
        state: absent
